<!DOCTYPE html>
<html lang="en" style="font-family:sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;font-size:10px;-webkit-tap-highlight-color:rgba(0,0,0,0)">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Intact Trading Account</title>
   </head>
  <body style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;font-family:&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif;font-size:14px;line-height:1.42857143;color:#333;font-family:'Raleway', sans-serif;background-color:#fff;margin:0;padding:0;font-size:16px;font-weight:normal;color:#000">
    <div id="header" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;display:block;border-top:13px solid #45ab5a;background:#1a2428;margin:10px 0 0;background-image: url(http://eoffice.intactfx.com/img/email/miniaccountcreated/header-bg.jpg); no-repeat 0 0;height:337px;background-size:cover">
      <div class="header-title" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;margin:221px 0 30px 13.5%;height:73px;border-top:3px solid #878683;border-left:3px solid #878683;border-bottom:3px solid #878683;-webkit-border-radius:40px 0 0 40px;-moz-border-radius:40px 0 0 40px;border-radius:40px 0 0 40px;clear:both;overflow:hidden;background:#45ab5a;padding:0 50px">
        <h1 style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;margin:.67em 0;font-size:2em;font-family:inherit;font-weight:500;line-height:1.1;color:inherit;margin-top:20px;margin-bottom:10px;font-size:36px;font-family:'Raleway', sans-serif;font-weight:normal;line-height:40px;margin:0 0 20px 0;font-size:34px;line-height:67px;color:#000;margin:0;font-weight:600">Congratulations on opening an IntactFX trading account!</h1>
      </div>
    </div>
    <!--/ header -->
    <section id="main" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;display:block;clear:both;overflow:hidden;background:#fff">
      <div class="container" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;padding-right:15px;padding-left:15px;margin-right:auto;margin-left:auto;width:1170px;background:#ffffff;overflow:hidden;padding-top:10px">
        <h2 style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;font-family:inherit;font-weight:500;line-height:1.1;color:inherit;margin-top:20px;margin-bottom:10px;font-size:30px;font-family:'Raleway', sans-serif;font-weight:normal;color:#000;font-size:26px;line-height:32px;margin:0 0 20px 0">Your trading account have been created. Here is your IntactFX Trading Account details:</h2>
      </div>
      <!--/ container -->
      <div class="green-bar" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;margin:0 0 10px 13.5%;border-top:3px solid #878683;border-left:3px solid #878683;border-bottom:3px solid #878683;-webkit-border-radius:80px 0 0 80px;-moz-border-radius:80px 0 0 80px;border-radius:80px 0 0 80px;clear:both;overflow:hidden;background:#45ab5a;padding:10px 0">
        <div class="green-content" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;max-width:605px;margin:0 20%">
          <table style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;border-spacing:0;border-collapse:collapse;background-color:transparent;width:100%;background:#fff;border:none;background:unset;border-spacing:2px !important;border-collapse:unset !important">
            <tr style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box">
              <td style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;padding:0;font-weight:600;font-size:20px;line-height:22px;margin:0 0 10px 0;color:#000;padding:3px">Trading Account Number:</td>
              <td class="text-right" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;padding:0;text-align:right;font-weight:600;font-size:20px;line-height:22px;margin:0 0 10px 0;color:#000;padding:3px">{{ $account['login'] }}</td>
            </tr>
            <tr style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box">
              <td style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;padding:0;font-weight:600;font-size:20px;line-height:22px;margin:0 0 10px 0;color:#000;padding:3px">Trader’s Password:</td>
              <td class="text-right" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;padding:0;text-align:right;font-weight:600;font-size:20px;line-height:22px;margin:0 0 10px 0;color:#000;padding:3px">{{ $account['password'] }}</td>
            </tr>
            <tr style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box">
              <td style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;padding:0;font-weight:600;font-size:20px;line-height:22px;margin:0 0 10px 0;color:#000;padding:3px">Investor’s Password:</td>
              <td class="text-right" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;padding:0;text-align:right;font-weight:600;font-size:20px;line-height:22px;margin:0 0 10px 0;color:#000;padding:3px">{{ $account['password_investor'] }}</td>
            </tr>
            <tr style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box">
              <td style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;padding:0;font-weight:600;font-size:20px;line-height:22px;margin:0 0 10px 0;color:#000;padding:3px">Trading Server Address:</td>
              <td class="text-right" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;padding:0;text-align:right;font-weight:600;font-size:20px;line-height:22px;margin:0 0 10px 0;color:#000;padding:3px">real1.intactfx.com:443</td>
            </tr>
            <tr style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box">
              <td style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;padding:0;font-weight:600;font-size:20px;line-height:22px;margin:0 0 10px 0;color:#000;padding:3px">Email:</td>
              <td class="text-right" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;padding:0;text-align:right;font-weight:600;font-size:20px;line-height:22px;margin:0 0 10px 0;color:#000;padding:3px">{{ $user->email }}</td>
            </tr>
          </table>
        </div>
      </div>
      <div class="container" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;padding-right:15px;padding-left:15px;margin-right:auto;margin-left:auto;width:1170px;background:#ffffff;overflow:hidden;padding-top:10px">
        <h2 style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;font-family:inherit;font-weight:500;line-height:1.1;color:inherit;margin-top:20px;margin-bottom:10px;font-size:30px;font-family:'Raleway', sans-serif;font-weight:normal;color:#000;font-size:26px;line-height:32px;margin:0 0 20px 0">If you have questions, comments or trouble logging in, please <a href="#" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;background-color:transparent;color:#337ab7;color:#2a3acf;text-decoration:none">Contact Us</a>
        </h2>
        <h3 style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;font-family:inherit;font-weight:500;line-height:1.1;color:inherit;margin-top:20px;margin-bottom:10px;font-size:24px;font-family:'Raleway', sans-serif;font-weight:normal;color:#000;font-size:22px;line-height:26px;margin:0 0 10px 0">Thank you!</h3>
        <h3 style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;font-family:inherit;font-weight:500;line-height:1.1;color:inherit;margin-top:20px;margin-bottom:10px;font-size:24px;font-family:'Raleway', sans-serif;font-weight:normal;color:#000;font-size:22px;line-height:26px;margin:0 0 10px 0">IntactFX Support Department</h3>
        <h3 style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;font-family:inherit;font-weight:500;line-height:1.1;color:inherit;margin-top:20px;margin-bottom:10px;font-size:24px;font-family:'Raleway', sans-serif;font-weight:normal;color:#000;font-size:22px;line-height:26px;margin:0 0 10px 0"><a href="#http://www.intactfx.com" target="_blank" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;background-color:transparent;color:#337ab7;color:#2a3acf;text-decoration:none">http://www.intactfx.com</a></h3>
        <hr style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;height:0;-webkit-box-sizing:content-box;-moz-box-sizing:content-box;box-sizing:content-box;margin-top:20px;margin-bottom:20px;border:0;border-top:1px solid #eee;border:3px solid #45ab5a;clear:both;overflow:hidden">
        <h2 style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;font-family:inherit;font-weight:500;line-height:1.1;color:inherit;margin-top:20px;margin-bottom:10px;font-size:30px;font-family:'Raleway', sans-serif;font-weight:normal;color:#000;font-size:26px;line-height:32px;margin:0 0 20px 0">How to use the details?</h2>
        <h3 class="clear" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;font-family:inherit;font-weight:500;line-height:1.1;color:inherit;margin-top:20px;margin-bottom:10px;font-size:24px;font-family:'Raleway', sans-serif;font-weight:normal;color:#000;font-size:22px;line-height:26px;margin:0 0 10px 0;overflow:hidden;clear:both">
          <span class="semibold" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;font-weight:600 !important">1. Trading Account Number</span> <span class="fr" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;float:right">- your “Login" for the MetaTrader 4 Trading Terminal.</span>
        </h3>
        <h3 class="clear" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;font-family:inherit;font-weight:500;line-height:1.1;color:inherit;margin-top:20px;margin-bottom:10px;font-size:24px;font-family:'Raleway', sans-serif;font-weight:normal;color:#000;font-size:22px;line-height:26px;margin:0 0 10px 0;overflow:hidden;clear:both">
          <span class="semibold" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;font-weight:600 !important">2. Trader’s Password</span> <span class="fr" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;float:right">- auto generated password used to access the trading account in MetaTrader 4</span>
        </h3>
        <h3 class="clear" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;font-family:inherit;font-weight:500;line-height:1.1;color:inherit;margin-top:20px;margin-bottom:10px;font-size:24px;font-family:'Raleway', sans-serif;font-weight:normal;color:#000;font-size:22px;line-height:26px;margin:0 0 10px 0;overflow:hidden;clear:both">
          <span class="semibold" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;font-weight:600 !important">3. Investor’s Password</span> <span class="fr text-right" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;text-align:right;float:right">- used to access the trading account in MetaTrader 4 but only to review 
                                <br style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box">
            account activities. The Investor`s password does not allow trading operations' execution. </span>
        </h3>
        <h3 class="clear" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;font-family:inherit;font-weight:500;line-height:1.1;color:inherit;margin-top:20px;margin-bottom:10px;font-size:24px;font-family:'Raleway', sans-serif;font-weight:normal;color:#000;font-size:22px;line-height:26px;margin:0 0 10px 0;overflow:hidden;clear:both">
          <span class="semibold" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;font-weight:600 !important">4. Trading Server Address</span> <span class="fr" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;float:right">- to be put in server section in MetaTrader 4 Trading Terminal.</span>
        </h3>
        <div class="gap" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;clear:both;overflow:hidden;height:30px"></div>
        <h3 class="text-center semibold" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;font-family:inherit;font-weight:500;line-height:1.1;color:inherit;margin-top:20px;margin-bottom:10px;font-size:24px;font-family:'Raleway', sans-serif;font-weight:normal;color:#000;font-size:22px;line-height:26px;margin:0 0 10px 0;text-align:center;font-weight:600 !important">We wish you success in trading using IntactFX | Making A Difference</h3>
        <hr style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;height:0;-webkit-box-sizing:content-box;-moz-box-sizing:content-box;box-sizing:content-box;margin-top:20px;margin-bottom:20px;border:0;border-top:1px solid #eee;border:3px solid #45ab5a;clear:both;overflow:hidden">
        <h2 style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;font-family:inherit;font-weight:500;line-height:1.1;color:inherit;margin-top:20px;margin-bottom:10px;font-size:30px;font-family:'Raleway', sans-serif;font-weight:normal;color:#000;font-size:26px;line-height:32px;margin:0 0 20px 0">What’s next?</h2>
        <h3 style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;font-family:inherit;font-weight:500;line-height:1.1;color:inherit;margin-top:20px;margin-bottom:10px;font-size:24px;font-family:'Raleway', sans-serif;font-weight:normal;color:#000;font-size:22px;line-height:26px;margin:0 0 10px 0">1. <a href="#" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;background-color:transparent;color:#337ab7;color:#2a3acf;text-decoration:none">Login</a> to your E-Office</h3>
        <h3 style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;font-family:inherit;font-weight:500;line-height:1.1;color:inherit;margin-top:20px;margin-bottom:10px;font-size:24px;font-family:'Raleway', sans-serif;font-weight:normal;color:#000;font-size:22px;line-height:26px;margin:0 0 10px 0">2. <a href="#" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;background-color:transparent;color:#337ab7;color:#2a3acf;text-decoration:none">Upload</a> your ID for account verification before you can start request for withdrawal</h3>
        <h3 style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;font-family:inherit;font-weight:500;line-height:1.1;color:inherit;margin-top:20px;margin-bottom:10px;font-size:24px;font-family:'Raleway', sans-serif;font-weight:normal;color:#000;font-size:22px;line-height:26px;margin:0 0 10px 0">3. <a href="#" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;background-color:transparent;color:#337ab7;color:#2a3acf;text-decoration:none">Deposit</a> your account as minimum of 25$ to start your trading</h3>
        <h3 style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;font-family:inherit;font-weight:500;line-height:1.1;color:inherit;margin-top:20px;margin-bottom:10px;font-size:24px;font-family:'Raleway', sans-serif;font-weight:normal;color:#000;font-size:22px;line-height:26px;margin:0 0 10px 0">4. <a href="#" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;background-color:transparent;color:#337ab7;color:#2a3acf;text-decoration:none">Download</a> and install Metatrader 4. Go to Appstore for ios and Google Playstore for Android device</h3>
        <hr style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;height:0;-webkit-box-sizing:content-box;-moz-box-sizing:content-box;box-sizing:content-box;margin-top:20px;margin-bottom:20px;border:0;border-top:1px solid #eee;border:3px solid #45ab5a;clear:both;overflow:hidden">
        <p class="text-center" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;margin:0 0 10px;text-align:center">If you would like to unsubscribe and stop receiving our newsletters, please click <a href="#" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;background-color:transparent;color:#337ab7;color:#2a3acf;text-decoration:none">here</a></p>
      </div>
    </section>
    <!--/ section main -->
    <footer id="footer" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;display:block;padding:30px 0 5px;clear:both;font-size:16px;color:#000;margin:0;background:#fff;overflow:hidden;border-bottom:15px solid #45ab5a">
      <div class="container" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;padding-right:15px;padding-left:15px;margin-right:auto;margin-left:auto;width:1170px">
        <div class="col-md-4" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;position:relative;min-height:1px;padding-right:15px;padding-left:15px;width:33.33333%;float:left">
          <img src="{{url('img/email/miniaccountcreated/footer-logo.png') }}" alt="footer logo" title="intactfx" class="footer-logo" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;border:0;vertical-align:middle">
        </div>
        <div class="col-md-8" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;position:relative;min-height:1px;padding-right:15px;padding-left:15px;width:60%;float:left">
          <div class="socialmedia" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;text-align:right;clear:both;overflow:hidden;margin:0 0 25px 0">
            <h3 class="semibold" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;font-family:inherit;font-weight:500;line-height:1.1;color:inherit;margin-top:20px;margin-bottom:10px;font-size:24px;font-family:'Raleway', sans-serif;font-weight:normal;color:#000;font-size:22px;line-height:26px;margin:0 0 10px 0;display:inline-block;margin:0 15px 0 0;font-weight:600 !important">Connect with us:</h3>
            <a href="#" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;background-color:transparent;color:#337ab7;color:#2a3acf;text-decoration:none"><img src="{{url('img/email/miniaccountcreated/facebook.png')}}" alt="facebook" title="facebook" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;border:0;vertical-align:middle;display:inline-block;margin:0 15px 15px"></a>
            <a href="#" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;background-color:transparent;color:#337ab7;color:#2a3acf;text-decoration:none"><img src="{{url('img/email/miniaccountcreated/google.png')}}" alt="google" title="google" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;border:0;vertical-align:middle;display:inline-block;margin:0 15px 15px"></a>
            <a href="#" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;background-color:transparent;color:#337ab7;color:#2a3acf;text-decoration:none"><img src="{{url('img/email/miniaccountcreated/twitter.png')}}" alt="twitter" title="twitter" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;border:0;vertical-align:middle;display:inline-block;margin:0 15px 15px"></a>
            <a href="#" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;background-color:transparent;color:#337ab7;color:#2a3acf;text-decoration:none"><img src="{{url('img/email/miniaccountcreated/pinterest.png')}}" alt="pinterest" title="pinterest" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;border:0;vertical-align:middle;display:inline-block;margin:0 15px 15px"></a>
            <a href="#" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;background-color:transparent;color:#337ab7;color:#2a3acf;text-decoration:none"><img src="{{url('img/email/miniaccountcreated/linkedin.png')}}" alt="linkedin" title="linkedin" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;border:0;vertical-align:middle;display:inline-block;margin:0 15px 15px"></a>
          </div>
          <h3 class="semibold text-right" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;font-family:inherit;font-weight:500;line-height:1.1;color:inherit;margin-top:20px;margin-bottom:10px;font-size:24px;font-family:'Raleway', sans-serif;font-weight:normal;color:#000;font-size:22px;line-height:26px;margin:0 0 10px 0;text-align:right;font-weight:600 !important">Intact Group Corporation</h3>
          <h3 class="text-right" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;font-family:inherit;font-weight:500;line-height:1.1;color:inherit;margin-top:20px;margin-bottom:10px;font-size:24px;font-family:'Raleway', sans-serif;font-weight:normal;color:#000;font-size:22px;line-height:26px;margin:0 0 10px 0;text-align:right">455, Foggy Heights, AZ 85004 United Kingdom</h3>
          <h3 class="text-right" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;font-family:inherit;font-weight:500;line-height:1.1;color:inherit;margin-top:20px;margin-bottom:10px;font-size:24px;font-family:'Raleway', sans-serif;font-weight:normal;color:#000;font-size:22px;line-height:26px;margin:0 0 10px 0;text-align:right">Contact us: (602) 519-0450 &nbsp;|&nbsp; Email us: support@intactfx.com</h3>
        </div>
        <div class="clear" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;overflow:hidden;clear:both"></div>
        <hr style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;height:0;-webkit-box-sizing:content-box;-moz-box-sizing:content-box;box-sizing:content-box;margin-top:20px;margin-bottom:20px;border:0;border-top:1px solid #eee;border:3px solid #45ab5a;clear:both;overflow:hidden">
        <p class="text-center" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;margin:0 0 10px;text-align:center">Intact Group Corporation, 2014 - 2016 &nbsp;|&nbsp; <a href="#" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;background-color:transparent;color:#337ab7;color:#2a3acf;text-decoration:none">Privacy Policy</a> &nbsp;|&nbsp; <a href="#" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;background-color:transparent;color:#337ab7;color:#2a3acf;text-decoration:none">Legal</a></p>
        <div class="gap" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;clear:both;overflow:hidden;height:30px"></div>
        <p class="text-center semibold nomargin" style="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;margin:0 0 10px;text-align:center;margin:0 !important;font-weight:600 !important">Do not print this message unless it is necessary, consider the environment.</p>
      </div>
    </footer>

  </body>
</html>